GET http://localhost:3000/commerce
###
POST  http://localhost:3000/post
###
PUT  http://localhost:3000/put
###
DELETE  http://localhost:3000/delete
###
GET http://localhost:3000/commercetest/3
###
GET http://localhost:3000/commercetest
###
GET http://localhost:3000/commercetest/filtreId/2
###
GET http://localhost:3000/commercetest/stats/1
###
PUT  http://localhost:3000/commercetest/updateC
### 
GET http://localhost:3000/test/2
###

GET http://localhost:3000/commercetest/user/2
###
GET http://localhost:3000//commercetest/login/commerce@gmail.com/123456
###
GET http://localhost:3000/test/2
###
POST http://localhost:3000/test/sportExpert/123 Ste Catherine A1B 1C1/sportExpert@mail.com/toto123
###
GET http://localhost:3000/test/login/iga@mail.com/123456
###
PUT http://localhost:3000/update/horaire/9,22,10,20,1
###
PUT http://localhost:3000/update/commerce/IGA_test,test,iga@test.com,654321,2
GET http://localhost:3000/test/couleur
###
GET http://localhost:3000/test/filtre

###
POST http://localhost:3000/test/employecreation/employee3/employee3@mail.com/qwerty2/3
###
POST http://localhost:3000/test/servicesCreation/service femmes/15
###
