GET http://localhost:3000/commerce
###
POST  http://localhost:3000/post
###
PUT  http://localhost:3000/put
###
DELETE  http://localhost:3000/delete
###
GET http://localhost:3000/commercetest/3
###
GET http://localhost:3000/commercetest
###
GET http://localhost:3000/commercetest/filtreId/2
###
GET http://localhost:3000/commercetest/stats/1
###
PUT  http://localhost:3000/commercetest/updateC
### 
GET http://localhost:3000/test/2
###

GET http://localhost:3000/commercetest/user/2
###
GET http://localhost:3000//commercetest/login/commerce@gmail.com/123456
###
GET http://localhost:3000/test/2
###
POST http://localhost:3000/test/boutique/123 Victoria A1B 1C1/boutique@mail.com/toto123
###
POST http://localhost:3000/test/login/iga@mail.com/123456
